language: php
php:
- 5.6
- 7.0
- 7.1
install:
- composer install
script:
- php ./vendor/bin/phpunit

notifications:
  slack:
    secure: qdnWCv8uzoFXqfz15RoUDoCnUwlcpI/qsyNayiHLS44ZAdP6l1rgbCmhtoofbSM8hMCILaiLb8UedVTDnPmT95kGnqDFfigNi0GDw6r9fpIzs+BNDNs6r0ZylH/7d+TKXF+dvBUD3KnbouxzsUx0QRO/Rz0xkfLWYZTRw8YBeHxF2AHy+1MA4V4NFtQlgwqJVYFvSAPyZJihRp5nyarB9J4YYTv7LRvuxSU9yPiIRQguVUtBT5jNcMtdmYF6sEV711NTw4zllDn3ZnjxF99ngI+VBCoaaaqvD3KHiFpHweCw+hmjoeMy954wMV6AyQiFOhHFVxs8kn5ySpNztxUJ9gtdtSU+HLMlhk820OQ9/hC2NuaKeN/jYei6erpb4zwDKo51CDCWgiCQo3NoQaBII+4alcX2iYhAdefX7A3N23Fo0Zd/C9Vo7H1UOKVDzzeW5cZyoCqj0hMpnilrLiXjNZceTXN/2vKOrOaikfdBXC7k9AJ82TDGLcbEAkDygvysVY6ly+fFrOhA0AC8TuwwP5Fi2+ccGU2jOsszaERfl9uUGK19paT5TLCneIQxno8KhhJSr3oa/OJOpmtCFTKfO4kPWZWXaO/rEltCyi1If45W5wkZ/nGxFp1N8BywqvybUPdNTByRwXKIYU6xyd7LpM5snDfyaficRsrxbkMqCf8=
